spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eldocument_v2
    username: root
    password: Pidraxuy111
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: c2Zqa3NkamZranNkbGtqZmtsc2pka2ZqdmJjeHZic2JkZmJzamtkZA==
    access: 365