spring:
  datasource:
    url: jdbc:mysql://localhost:3306/el_document?createDatabaseIfNotExist=true
    username: root
    password: ggtt1234
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: c2Zqa3NkamZranNkbGtqZmtsc2pka2ZqdmJjeHZic2JkZmJzamtkZA==
    access: 365